2017-03-09 20:21:22 [ main:0 ] - [ ERROR ] org.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: [dtx.oa.rbac.model.Node#ff80808159ac6d4b0159ac755ebf0002]
2017-03-09 20:21:22 [ main:16 ] - [ ERROR ] org.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: [dtx.oa.rbac.model.Node#ff80808159ac6d4b0159ac755ebf0002]
2017-03-09 20:22:44 [ main:0 ] - [ ERROR ] org.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: [dtx.oa.rbac.model.Node#ff80808159ac6d4b0159ac755ebf0002]
2017-03-09 20:22:44 [ main:17 ] - [ ERROR ] org.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: [dtx.oa.rbac.model.Node#ff80808159ac6d4b0159ac755ebf0002]
2017-03-09 20:23:56 [ main:0 ] - [ ERROR ] org.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: [dtx.oa.rbac.model.Node#ff80808159ac6d4b0159ac755ebf0002]
2017-03-09 20:23:56 [ main:17 ] - [ ERROR ] org.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: [dtx.oa.rbac.model.Node#ff80808159ac6d4b0159ac755ebf0002]
2017-03-09 20:24:29 [ main:0 ] - [ ERROR ] org.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: [dtx.oa.rbac.model.Node#ff80808159ac6d4b0159ac755ebf0002]
2017-03-09 20:24:29 [ main:16 ] - [ ERROR ] org.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: [dtx.oa.rbac.model.Node#ff80808159ac6d4b0159ac755ebf0002]
